@startuml
!pragma useVerticalIf on        
rectangle LA as "Logical Architecture" {
    rectangle "[L] AIDA" {
        rectangle "[L] Drone" as Drone {
            rectangle FlightControl as "[L] Flight Control & Monitoring" {
                rectangle "LogFun_1" #lightblue
                rectangle "LogFun_3" #LightSeaGreen
                rectangle "LogFun_4_4" #LightGreen
                rectangle "LogFun_4_5" #LightGreen
                rectangle "LogFun_4_8" #LightGreen
                rectangle "LogFun_4_9" #LightGreen
                rectangle "LogFun_6_1" #LightPink
                
            }
            rectangle PL as "[L] Payload"
            rectangle PS as "[L] Propulsion System"{
                rectangle "LogFun_4_6" #LightGreen
                rectangle "LogFun_5_2" #LightSalmon
            }
            rectangle STR as "[L] Structure"{
                rectangle "LogFun_4_10" #LightGreen
            }
        }
        rectangle DESK as "[L] Control Desk" {
                rectangle "LogFun_4_7" #LightGreen
                rectangle "LogFun_2" #LightCyan
                rectangle "LogFun_5_1" #LightSalmon
                rectangle "LogFun_5_3" #LightSalmon
                rectangle "LogFun_6_2" #LightPink
                rectangle "LogFun_7" #LightGoldenRodYellow
            }
        rectangle REMOTE as "[L] Remote Control"{
                rectangle "LogFun_4_1" #LightGreen
                rectangle "LogFun_4_2" #LightGreen
                rectangle "LogFun_4_3" #LightGreen
                rectangle "LogFun_6_3" #LightPink
            }
    }
DESK -[hidden]u-> REMOTE
    rectangle OP as "[LA] Drone Operator"
    rectangle MGMNT as "[LA] Air Traffic Management & Airport Authorities"
    rectangle ENV as "[LA] Drone Environment"
    rectangle AC as "[LA] Aircraft"
    rectangle DTBS as "[LA] Airline Database"
}

rectangle "Functions" as Functions {
    rectangle LF1 as "[LogFun_1] Provide direct remote identification information" #lightblue
    rectangle LF2 as "[LogFun_2] Manage mission" #LightCyan
    rectangle LF3 as "[LogFun_3] Sense drone state and environment" #LightSeaGreen
    rectangle LF4 as "[LogFun_4] Control drone motion" #LightGreen
    rectangle LF5 as "[LogFun_5] Acquire visual information" #LightSalmon
    rectangle LF6 as "[LogFun_6] Detect AIDA failures" #LightPink
    rectangle LF7 as "[LogFun_7] Analyse acquired visual information" #LightGoldenRodYellow
}
LF1 -[hidden]d-> LF2
LF3 -[hidden]d-> LF4
rectangle HELP as " "
HELP -[hidden]r-> LA
HELP -[hidden]r-> Functions
LA --[hidden]d--> Functions
Drone -[hidden]l-> OP
AC -[hidden]l-> Drone
@enduml